### PR TITLE
[bugfix] crash on master branch

### LINKED ISSUE #110: Crash on master branch

### PR DESCRIPTION
**Pull request by Kaaveh**
There was a crash on master branch when navigated from Market list to details screen
Close #110

### CODE REVIEW

File: library/navigation/src/main/java/ir/composenews/navigation/graph/FavoriteNews.kt [hunk 1]
```diff
@@ -31,7 +31,7 @@ fun NavGraphBuilder.favoriteList(
             ContentType.DUAL_PANE -> {
                 val market =
                     entry.parcelableData<MarketModel>(Destinations.MarketDetailScreen().market)
-                        ?: (uiState.market as? MarketModel?)
+                        ?: uiState.market
```
Comment (VahidGarousi) [inline library/navigation/src/main/java/ir/composenews/navigation/graph/FavoriteNews.kt:34]: Why you remove this `as? MarketNodel?`?

Comment (Kaaveh) [reply library/navigation/src/main/java/ir/composenews/navigation/graph/FavoriteNews.kt:34]: Because I changed `val market: Any? = null` to `val market: MarketModel? = null`, so this casting not require anymore.

**Comment by Kaaveh** [comment]
> I carefully checked the codes and did not see any problems

It caused a runtime crash.
